# 1. Libraries
---

In [12]:
from sqlalchemy import create_engine, Table, Column, Integer, MetaData, Float, TEXT, Date, BIGINT, INT
from datetime import datetime
from dotenv import load_dotenv
import pandas as pd
import os

load_dotenv()

True

# 2. Extract
---

In [13]:
df = pd.read_csv('../data/real_estate_dataset.csv')
df.head()

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747
1,2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386
2,3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880
3,4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996
4,5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523

# 3. Transform
---

In [14]:
# date
now = datetime.now()
ts = int(datetime.timestamp(now)* 1000)
df['created_at'] = ts

df.head()

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price,created_at
0,1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747,1771884631731
1,2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386,1771884631731
2,3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880,1771884631731
3,4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996,1771884631731
4,5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523,1771884631731

In [15]:
# lower columns title
df.columns = df.columns.str.lower()
df.head()

,id,square_feet,num_bedrooms,num_bathrooms,num_floors,year_built,has_garden,has_pool,garage_size,location_score,distance_to_center,price,created_at
0,1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747,1771884631731
1,2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386,1771884631731
2,3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880,1771884631731
3,4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996,1771884631731
4,5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523,1771884631731

In [16]:
# index 
df = df.set_index('id')
df.head()

,square_feet,num_bedrooms,num_bathrooms,num_floors,year_built,has_garden,has_pool,garage_size,location_score,distance_to_center,price,created_at
id,,,,,,,,,,,,
1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747,1771884631731
2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386,1771884631731
3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880,1771884631731
4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996,1771884631731
5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523,1771884631731

# 4. Load
---

In [ ]:
# Start engine
postgres_database = os.environ["HOUSING_PRICES_DATABASE"]
engine = create_engine(postgres_database, echo=True)

# create table
metadata = MetaData()
table_name = 'housing_prices'

my_table = Table(
    table_name, metadata,
    Column('id', Integer, primary_key=True),
    Column('square_feet', Float),
    Column('num_bedrooms', Integer),
    Column('num_bathrooms', Integer),
    Column('num_floors', Integer),
    Column('year_built', Integer),
    Column('has_garden', Integer),
    Column('has_pool', Integer),
    Column('garage_size', Integer),
    Column('location_score', Float),
    Column('distance_to_center', Float),
    Column('price', Float),
    Column('price_predict', Float),
    Column('created_at', TEXT)
)

#run the engine
metadata.create_all(engine)

2026-02-23 23:11:21,328 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2026-02-23 23:11:21,329 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-02-23 23:11:21,382 INFO sqlalchemy.engine.Engine select current_schema()
2026-02-23 23:11:21,382 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-02-23 23:11:21,432 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2026-02-23 23:11:21,432 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-02-23 23:11:21,482 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-02-23 23:11:21,484 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-02-23 23:11:21,484 INFO sqlalchemy.engine.Engine [generated in 0.00041s] {'table_name': 'housing_prices', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-02-23 23:11:21,537 INFO sqlalchemy.engine.Engine
CREATE TABLE housing_prices (
	id SERIAL NOT NULL,
	square_feet FLOAT,
	num_bedrooms INTEGER,
	num_bathrooms INTEGER,
	num_floors INTEGER,
	year_built INTEGER,
	has_garden INTEGER,
	has_pool INTEGER,
	garage_size INTEGER,
	location_score FLOAT,
	distance_to_center FLOAT,
	price FLOAT,
	price_predict FLOAT,
	created_at TEXT,
	PRIMARY KEY (id)
)


2026-02-23 23:11:21,537 INFO sqlalchemy.engine.Engine [no key 0.00045s] {}
2026-02-23 23:11:21,587 INFO sqlalchemy.engine.Engine COMMIT

In [19]:
# load data
df.to_sql(table_name, engine, if_exists="append")

2026-02-23 23:11:24,573 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-02-23 23:11:24,575 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2026-02-23 23:11:24,575 INFO sqlalchemy.engine.Engine [cached since 3.092s ago] {'table_name': 'housing_prices', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2026-02-23 23:11:24,634 INFO sqlalchemy.engine.Engine INSERT INTO housing_prices (id, square_feet, num_bedrooms, num_bathrooms, num_floors, year_built, has_garden, has_pool, garage_size, location_score, distance_to_center, price, created_at) VALUES (%(id__0)s, %(square_feet__0)s, %(num_bedrooms__0)s, %( ... 137913 characters truncated ... e__499)s, %(location_score__499)s, %(distance_to_center__499)s, %(price__499)s, %(created_at__499)s)
2026-02-23 23:11:24,634 INFO sqlalchemy.engine.Engine [generated in 0.00178s (insertmanyvalues) 1/1 (unordered)] {'location_score__0': 8.297631202876449, 'garage_size__0': 48, 'distance_to_center__0': 5.935733640397012, 'has_garden__0': 1, 'has_pool__0': 1, 'price__0': 602134.816746586, 'num_floors__0': 3, 'num_bathrooms__0': 3, 'id__0': 1, 'square_feet__0': 143.63502971184062, 'year_built__0': 1967, 'created_at__0': 1771884631731, 'num_bedrooms__0': 1, 'location_score__1': 6.061465649334798, 'garage_size__1': 37, 'distance_to_center__1': 10.827392203145374, 'has_garden__1': 0, 'has_pool__1': 1, 'price__1': 591425.1353862194, 'num_floors__1': 1, 'num_bathrooms__1': 2, 'id__1': 2, 'square_feet__1': 287.67857660247904, 'year_built__1': 1949, 'created_at__1': 1771884631731, 'num_bedrooms__1': 1, 'location_score__2': 2.9114424778517902, 'garage_size__2': 14, 'distance_to_center__2': 6.904599073399449, 'has_garden__2': 1, 'has_pool__2': 0, 'price__2': 464478.6968798775, 'num_floors__2': 2, 'num_bathrooms__2': 3, 'id__2': 3, 'square_feet__2': 232.99848545285127, 'year_built__2': 1923, 'created_at__2': 1771884631731, 'num_bedrooms__2': 1, 'location_score__3': 2.0709491817657124, 'garage_size__3': 17, 'distance_to_center__3': 8.284018511436607, 'has_garden__3': 0, 'has_pool__3': 0, 'price__3': 583105.655996478, 'num_floors__3': 2, 'num_bathrooms__3': 2, 'id__3': 4, 'square_feet__3': 199.66462104925915, 'year_built__3': 1918 ... 6400 parameters truncated ... 'distance_to_center__496': 2.8451047955363085, 'has_garden__496': 0, 'has_pool__496': 1, 'price__496': 657736.9217174305, 'num_floors__496': 1, 'num_bathrooms__496': 3, 'id__496': 497, 'square_feet__496': 195.914027962718, 'year_built__496': 1977, 'created_at__496': 1771884631731, 'num_bedrooms__496': 2, 'location_score__497': 8.629723989869625, 'garage_size__497': 18, 'distance_to_center__497': 6.263264036595542, 'has_garden__497': 0, 'has_pool__497': 0, 'price__497': 405324.9502010681, 'num_floors__497': 2, 'num_bathrooms__497': 1, 'id__497': 498, 'square_feet__497': 69.4336592412462, 'year_built__497': 2004, 'created_at__497': 1771884631731, 'num_bedrooms__497': 1, 'location_score__498': 5.318890790075141, 'garage_size__498': 41, 'distance_to_center__498': 16.990684309758027, 'has_garden__498': 1, 'has_pool__498': 0, 'price__498': 773035.968027659, 'num_floors__498': 3, 'num_bathrooms__498': 1, 'id__498': 499, 'square_feet__498': 293.5987019165416, 'year_built__498': 1940, 'created_at__498': 1771884631731, 'num_bedrooms__498': 5, 'location_score__499': 7.894321941951912, 'garage_size__499': 20, 'distance_to_center__499': 1.7797942971269332, 'has_garden__499': 1, 'has_pool__499': 1, 'price__499': 864299.5002175039, 'num_floors__499': 1, 'num_bathrooms__499': 3, 'id__499': 500, 'square_feet__499': 296.5526861199007, 'year_built__499': 1988, 'created_at__499': 1771884631731, 'num_bedrooms__499': 4}
2026-02-23 23:11:24,732 INFO sqlalchemy.engine.Engine COMMIT

500